version: '3.4'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    networks:
      - dockernet
    ports:
      - "5432:5432"

  app:
    image: ${DOCKER_REGISTRY-}app
    depends_on:
      - db
    environment:
      - DB_HOST=db
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - dockernet
    ports:
      - "8080:8080"

networks:
  dockernet:
