name: 'deploy'

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: 'pils-frontend/package-lock.json'

      - name: Build frontend
        working-directory: ./pils-frontend
        run: |
          npm install
          npm run build

      - name: Copy frontend
        run: cp -R pils-frontend/dist src/main/resources/static


      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package -DskipTests --file pom.xml

      - name: Show tree
        run: tree


      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: lassekl/pils:${{ github.sha }}

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@gataersamla.no:22/pils'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: lassekl/pils:${{ github.sha }}
